using Encore.Messaging;

namespace Amadeus.Messages.Responses;

public class SessionKeysResponse : IMessage
{
    public static Enum Command => ResponseCommand.SessionKeys;

    // Seed used to generate the keys. Not to be used in the actual decryption
    [MessageField(order: 0)]
    public short Seed { get; init; }

    // This is actually part of the Primary XOR Table, but guaranteed to be 0
    [MessageField(order: 1)]
    public byte Prefix { get; init; }

    // Random key to be xor-ed against credential request payload
    // In 9you, it only uses the first byte of the key, which is likely to be a bug on both client and server
    //
    // The key is generated by using `rand()` on each byte
    [CollectionMessageField(order: 2, minCount: 32, maxCount: 32)]
    public required byte[] PrimaryKey { get; init; }

    // Random key to be xor-ed against credential request payload
    // In 9you, it is completely ignored, which is likely to be a bug on both client and server
    //
    // The key is generated by using `rand()` on each byte
    [CollectionMessageField(order: 3, minCount: 16, maxCount: 16)]
    public required byte[] SecondaryKey { get; init; }
}