// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mozart.Data.Contexts;

#nullable disable

namespace Mozart.Migrations.Sqlite.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20260211061230_CreateUserMusicList")]
    partial class CreateUserMusicList
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("Mozart.Data.Entities.AcquiredMusic", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("USER_INDEX_ID");

                    b.Property<int>("MusicId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MUSIC_ID");

                    b.HasKey("UserId");

                    b.ToTable("t_o2jam_musiclist", (string)null);
                });

            modelBuilder.Entity("Mozart.Data.Entities.AuthSession", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("USER_INDEX_ID");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ADDR_IP");

                    b.Property<int>("ChannelId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SUB_CH");

                    b.Property<string>("GatewayId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("GATEWAY_ID");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("LOGIN_TIME");

                    b.Property<int>("ServerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MAIN_CH");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("TUSER_ID");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("USER_ID");

                    b.HasKey("UserId");

                    b.ToTable("t_o2jam_login", (string)null);
                });

            modelBuilder.Entity("Mozart.Data.Entities.Credential", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("passwd");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("userid");

                    b.Property<DateTime>("registdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("member", (string)null);
                });

            modelBuilder.Entity("Mozart.Data.Entities.Loadout", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("USER_INDEX_ID");

                    b.Property<short>("Bag1")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Bag10")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Bag11")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Bag12")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Bag13")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Bag14")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Bag15")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Bag16")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Bag17")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Bag18")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Bag19")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Bag2")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Bag20")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Bag21")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Bag22")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Bag23")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Bag24")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Bag25")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Bag26")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Bag27")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Bag28")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Bag29")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Bag3")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Bag30")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Bag4")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Bag5")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Bag6")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Bag7")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Bag8")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Bag9")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Equip1")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Equip10")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Equip11")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Equip12")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Equip13")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Equip14")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Equip15")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Equip16")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Equip2")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Equip3")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Equip4")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Equip5")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Equip6")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Equip7")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Equip8")
                        .HasColumnType("INTEGER");

                    b.Property<short>("Equip9")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.ToTable("t_o2jam_item", (string)null);
                });

            modelBuilder.Entity("Mozart.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("USER_INDEX_ID");

                    b.Property<int>("Battle")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Draw")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Experience")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Gender")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Sex");

                    b.Property<int>("IsAdministrator")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AdminLevel");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Lose")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("USER_NICKNAME");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("USER_ID");

                    b.Property<int>("Win")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");
                    
                    b.HasIndex("Username")
                        .IsUnique();
                    
                    b.HasIndex("Nickname")
                        .IsUnique();

                    b.ToTable("t_o2jam_charinfo", (string)null);
                });

            modelBuilder.Entity("Mozart.Data.Entities.UserRanking", b =>
                {
                    b.Property<int>("Ranking")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Ranking");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("User_Index_ID");

                    b.HasKey("Ranking");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("t_o2jam_dumpranking", (string)null);
                });

            modelBuilder.Entity("Mozart.Data.Entities.Wallet", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("USER_INDEX_ID");

                    b.Property<int>("Gem")
                        .HasColumnType("INTEGER");

                    b.Property<int>("O2Cash")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.ToTable("t_o2jam_charcash", (string)null);
                });

            modelBuilder.Entity("Mozart.Data.Entities.AcquiredMusic", b =>
                {
                    b.HasOne("Mozart.Data.Entities.User", null)
                        .WithMany("AcquiredMusicList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Mozart.Data.Entities.Loadout", b =>
                {
                    b.HasOne("Mozart.Data.Entities.User", null)
                        .WithOne("Loadout")
                        .HasForeignKey("Mozart.Data.Entities.Loadout", "UserId");
                });

            modelBuilder.Entity("Mozart.Data.Entities.UserRanking", b =>
                {
                    b.HasOne("Mozart.Data.Entities.User", null)
                        .WithOne("UserRanking")
                        .HasForeignKey("Mozart.Data.Entities.UserRanking", "UserId");
                });

            modelBuilder.Entity("Mozart.Data.Entities.Wallet", b =>
                {
                    b.HasOne("Mozart.Data.Entities.User", null)
                        .WithOne("Wallet")
                        .HasForeignKey("Mozart.Data.Entities.Wallet", "UserId");
                });

            modelBuilder.Entity("Mozart.Data.Entities.User", b =>
                {
                    b.Navigation("AcquiredMusicList");

                    b.Navigation("Loadout")
                        .IsRequired();

                    b.Navigation("UserRanking")
                        .IsRequired();

                    b.Navigation("Wallet")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
