namespace Mozart.Metadata;

public enum Arena : byte
{
    Random            = 0x80,
    Gravity           = 0x01,
    Manique           = 0x02,
    Cricket           = 0x03,
    GamicRoad         = 0x04,
    HonkyTonky        = 0x05,
    LarvaHouse        = 0x06,
    Monster           = 0x07,
    StreetBasketball  = 0x08,
    BasketballCourt   = 0x09,
    FootballField     = 0x0A,
    AWhaleOfAqua      = 0x0B,
    Halloween         = 0x0C,
    ArenaBridge       = 0x0D,
    Aqua              = 0x0E,
    AquaCubic         = 0x0F,
    AquaDeepSea       = 0x10,
    LarvaXMas         = 0x11,
    Hearth            = 0x12,
    PadangMerdeka     = 0x13,
    Taiwan            = 0x14,
    SkiResort         = 0x15,
    Beach             = 0x16,
    O2StockFarm       = 0x17,
    Athena            = 0x18,
    Santa             = 0x19,
    CrystalSki        = 0x1A,
    Concert           = 0x1B,
    Draconic          = 0x1C,
    ValentineJam      = 0x1D,
    Lunar             = 0x1E,
    Surfing           = 0x1F,
    WorldChampionHall = 0x20,
    O2Planet          = 0x21,
    Atlantis          = 0x22,
    NewHalloween      = 0x23,
    NewXMas           = 0x24,
}
