// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mozart.Data.Contexts;

#nullable disable

namespace Mozart.Migrations.MySql
{
    [DbContext(typeof(UserDbContext))]
    partial class UserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Mozart.Data.Entities.AuthSession", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("USER_INDEX_ID");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ADDR_IP");

                    b.Property<int>("ChannelId")
                        .HasColumnType("int")
                        .HasColumnName("SUB_CH");

                    b.Property<string>("GatewayId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("GATEWAY_ID");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("LOGIN_TIME");

                    b.Property<int>("ServerId")
                        .HasColumnType("int")
                        .HasColumnName("MAIN_CH");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TUSER_ID");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("USER_ID");

                    b.HasKey("UserId");

                    b.ToTable("t_o2jam_login", (string)null);
                });

            modelBuilder.Entity("Mozart.Data.Entities.Credential", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("passwd");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("userid");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("member", (string)null);
                });

            modelBuilder.Entity("Mozart.Data.Entities.Inventory", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("USER_INDEX_ID");

                    b.Property<short>("Bag1")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag10")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag11")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag12")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag13")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag14")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag15")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag16")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag17")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag18")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag19")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag2")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag20")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag21")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag22")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag23")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag24")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag25")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag26")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag27")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag28")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag29")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag3")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag30")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag4")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag5")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag6")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag7")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag8")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag9")
                        .HasColumnType("smallint");

                    b.Property<short>("Equip1")
                        .HasColumnType("smallint");

                    b.Property<short>("Equip10")
                        .HasColumnType("smallint");

                    b.Property<short>("Equip11")
                        .HasColumnType("smallint");

                    b.Property<short>("Equip12")
                        .HasColumnType("smallint");

                    b.Property<short>("Equip13")
                        .HasColumnType("smallint");

                    b.Property<short>("Equip14")
                        .HasColumnType("smallint");

                    b.Property<short>("Equip15")
                        .HasColumnType("smallint");

                    b.Property<short>("Equip16")
                        .HasColumnType("smallint");

                    b.Property<short>("Equip2")
                        .HasColumnType("smallint");

                    b.Property<short>("Equip3")
                        .HasColumnType("smallint");

                    b.Property<short>("Equip4")
                        .HasColumnType("smallint");

                    b.Property<short>("Equip5")
                        .HasColumnType("smallint");

                    b.Property<short>("Equip6")
                        .HasColumnType("smallint");

                    b.Property<short>("Equip7")
                        .HasColumnType("smallint");

                    b.Property<short>("Equip8")
                        .HasColumnType("smallint");

                    b.Property<short>("Equip9")
                        .HasColumnType("smallint");

                    b.HasKey("UserId");

                    b.ToTable("t_o2jam_item", (string)null);
                });

            modelBuilder.Entity("Mozart.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("USER_INDEX_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Battle")
                        .HasColumnType("int");

                    b.Property<int>("Draw")
                        .HasColumnType("int");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<bool>("Gender")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Sex");

                    b.Property<int>("IsAdministrator")
                        .HasColumnType("int")
                        .HasColumnName("AdminLevel");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("Lose")
                        .HasColumnType("int");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("USER_NICKNAME");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("USER_ID");

                    b.Property<int>("Win")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Username", "Nickname")
                        .IsUnique();

                    b.ToTable("t_o2jam_charinfo", (string)null);
                });

            modelBuilder.Entity("Mozart.Data.Entities.Wallet", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("USER_INDEX_ID");

                    b.Property<int>("Gem")
                        .HasColumnType("int");

                    b.Property<int>("O2Cash")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("t_o2jam_charcash", (string)null);
                });

            modelBuilder.Entity("Mozart.Data.Entities.Inventory", b =>
                {
                    b.HasOne("Mozart.Data.Entities.User", null)
                        .WithOne("Items")
                        .HasForeignKey("Mozart.Data.Entities.Inventory", "UserId");
                });

            modelBuilder.Entity("Mozart.Data.Entities.Wallet", b =>
                {
                    b.HasOne("Mozart.Data.Entities.User", null)
                        .WithOne("Wallet")
                        .HasForeignKey("Mozart.Data.Entities.Wallet", "UserId");
                });

            modelBuilder.Entity("Mozart.Data.Entities.User", b =>
                {
                    b.Navigation("Items")
                        .IsRequired();

                    b.Navigation("Wallet")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
