// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mozart.Data.Contexts;

#nullable disable

namespace Mozart.Migrations.SqlServer.Migrations
{
    [DbContext(typeof(MainDbContext))]
    partial class MainDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mozart.Data.Entities.AcquiredMusic", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("USER_INDEX_ID");

                    b.Property<int>("MusicId")
                        .HasColumnType("int")
                        .HasColumnName("MUSIC_ID");

                    b.HasKey("UserId");

                    b.ToTable("t_o2jam_musiclist", (string)null);
                });

            modelBuilder.Entity("Mozart.Data.Entities.AttributiveItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("INDEX_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AcquiredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("REG_DATE")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Count")
                        .HasColumnType("int")
                        .HasColumnName("USED_COUNT");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("ITEM_INDEX_ID");

                    b.Property<int>("PreviousCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("OLD_USED_COUNT");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("USER_INDEX_ID");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("t_o2jam_char_attr_item", (string)null);
                });

            modelBuilder.Entity("Mozart.Data.Entities.AuthSession", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("USER_INDEX_ID");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ADDR_IP");

                    b.Property<int>("ChannelId")
                        .HasColumnType("int")
                        .HasColumnName("SUB_CH");

                    b.Property<string>("GatewayId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("GATEWAY_ID");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("LOGIN_TIME");

                    b.Property<int>("ServerId")
                        .HasColumnType("int")
                        .HasColumnName("MAIN_CH");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TUSER_ID");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("USER_ID");

                    b.HasKey("UserId");

                    b.ToTable("t_o2jam_login", (string)null);
                });

            modelBuilder.Entity("Mozart.Data.Entities.GiftItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Seq");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("ItemID");

                    b.Property<DateTime>("SendDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("SendDate")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("SenderId")
                        .HasColumnType("int")
                        .HasColumnName("Sender_Index_ID");

                    b.Property<string>("SenderNickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SenderNickname");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_Index_ID");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("t_o2jam_gift_item", (string)null);
                });

            modelBuilder.Entity("Mozart.Data.Entities.GiftMusic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Seq");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MusicId")
                        .HasColumnType("int")
                        .HasColumnName("Music_ID");

                    b.Property<DateTime>("SendDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("SendDate")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("SenderId")
                        .HasColumnType("int")
                        .HasColumnName("Sender_Index_ID");

                    b.Property<string>("SenderNickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SenderNickname");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_Index_ID");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("t_o2jam_gift_music", (string)null);
                });

            modelBuilder.Entity("Mozart.Data.Entities.Loadout", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("USER_INDEX_ID");

                    b.Property<short>("Bag1")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag10")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag11")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag12")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag13")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag14")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag15")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag16")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag17")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag18")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag19")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag2")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag20")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag21")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag22")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag23")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag24")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag25")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag26")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag27")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag28")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag29")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag3")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag30")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag4")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag5")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag6")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag7")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag8")
                        .HasColumnType("smallint");

                    b.Property<short>("Bag9")
                        .HasColumnType("smallint");

                    b.Property<short>("Equip1")
                        .HasColumnType("smallint");

                    b.Property<short>("Equip10")
                        .HasColumnType("smallint");

                    b.Property<short>("Equip11")
                        .HasColumnType("smallint");

                    b.Property<short>("Equip12")
                        .HasColumnType("smallint");

                    b.Property<short>("Equip13")
                        .HasColumnType("smallint");

                    b.Property<short>("Equip14")
                        .HasColumnType("smallint");

                    b.Property<short>("Equip15")
                        .HasColumnType("smallint");

                    b.Property<short>("Equip16")
                        .HasColumnType("smallint");

                    b.Property<short>("Equip2")
                        .HasColumnType("smallint");

                    b.Property<short>("Equip3")
                        .HasColumnType("smallint");

                    b.Property<short>("Equip4")
                        .HasColumnType("smallint");

                    b.Property<short>("Equip5")
                        .HasColumnType("smallint");

                    b.Property<short>("Equip6")
                        .HasColumnType("smallint");

                    b.Property<short>("Equip7")
                        .HasColumnType("smallint");

                    b.Property<short>("Equip8")
                        .HasColumnType("smallint");

                    b.Property<short>("Equip9")
                        .HasColumnType("smallint");

                    b.HasKey("UserId");

                    b.ToTable("t_o2jam_item", (string)null);
                });

            modelBuilder.Entity("Mozart.Data.Entities.Member", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("passwd");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("userid");

                    b.Property<short>("Vip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("vip");

                    b.Property<DateTime>("VipDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("vipdate");

                    b.Property<DateTime>("registdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("member", (string)null);
                });

            modelBuilder.Entity("Mozart.Data.Entities.MusicScoreRecord", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("USER_INDEX_ID");

                    b.Property<int>("MusicId")
                        .HasColumnType("int")
                        .HasColumnName("MUSIC_INDEX_ID");

                    b.Property<byte>("Difficulty")
                        .HasColumnType("tinyint")
                        .HasColumnName("DIFFICULTY");

                    b.Property<byte>("ClearType")
                        .HasColumnType("tinyint")
                        .HasColumnName("FLAG");

                    b.Property<long>("Score")
                        .HasColumnType("bigint")
                        .HasColumnName("USER_SCORE");

                    b.HasKey("UserId", "MusicId", "Difficulty");

                    b.ToTable("t_o2jam_user_music_ranking", (string)null);
                });

            modelBuilder.Entity("Mozart.Data.Entities.Penalty", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("passwd");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("userid");

                    b.Property<DateTime>("registdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("member", (string)null);
                });

            modelBuilder.Entity("Mozart.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("USER_INDEX_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Battle")
                        .HasColumnType("int");

                    b.Property<int>("Draw")
                        .HasColumnType("int");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit")
                        .HasColumnName("Sex");

                    b.Property<int>("IsAdministrator")
                        .HasColumnType("int")
                        .HasColumnName("AdminLevel");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("Lose")
                        .HasColumnType("int");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("USER_NICKNAME");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("USER_ID");

                    b.Property<int>("Win")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nickname")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("t_o2jam_charinfo", (string)null);
                });

            modelBuilder.Entity("Mozart.Data.Entities.UserMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Seq");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("GiftType")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .HasColumnName("TypeFlag");

                    b.Property<string>("IsRead")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasDefaultValue("0")
                        .HasColumnName("ReadFlag");

                    b.Property<DateTime?>("ReadDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int")
                        .HasColumnName("ReceiverIndexID");

                    b.Property<string>("ReceiverNickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ReceiverNickName");

                    b.Property<string>("ReceiverUsername")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ReceiverID");

                    b.Property<int>("SenderId")
                        .HasColumnType("int")
                        .HasColumnName("SenderIndexID");

                    b.Property<string>("SenderNickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SenderNickName");

                    b.Property<string>("SenderUsername")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SenderID");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("WriteDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.ToTable("t_o2jam_message", (string)null);
                });

            modelBuilder.Entity("Mozart.Data.Entities.UserRanking", b =>
                {
                    b.Property<int>("Ranking")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Ranking");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ranking"));

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_Index_ID");

                    b.HasKey("Ranking");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("t_o2jam_dumpranking", (string)null);
                });

            modelBuilder.Entity("Mozart.Data.Entities.UserRankingExtended", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Seq");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Battle")
                        .HasColumnType("int")
                        .HasColumnName("Battle");

                    b.Property<int>("ChangeRanking")
                        .HasColumnType("int")
                        .HasColumnName("ChangeRanking");

                    b.Property<int>("ChangeType")
                        .HasColumnType("int")
                        .HasColumnName("ChangeType");

                    b.Property<int>("Draw")
                        .HasColumnType("int")
                        .HasColumnName("Draw");

                    b.Property<int>("Experience")
                        .HasColumnType("int")
                        .HasColumnName("Experience");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("Level");

                    b.Property<int>("Lose")
                        .HasColumnType("int")
                        .HasColumnName("Lose");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("User_NickName");

                    b.Property<int>("Ranking")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("Ranking");

                    b.Property<bool>("Sex")
                        .HasColumnType("bit")
                        .HasColumnName("Sex");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_Index_ID");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("User_ID");

                    b.Property<int>("Win")
                        .HasColumnType("int")
                        .HasColumnName("Win");

                    b.Property<DateTime>("WriteDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("WriteDate")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("t_o2jam_user_ranking", (string)null);
                });

            modelBuilder.Entity("Mozart.Data.Entities.Wallet", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("USER_INDEX_ID");

                    b.Property<int>("Gem")
                        .HasColumnType("int");

                    b.Property<int>("O2Cash")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("t_o2jam_charcash", (string)null);
                });

            modelBuilder.Entity("Mozart.Data.Entities.AcquiredMusic", b =>
                {
                    b.HasOne("Mozart.Data.Entities.User", null)
                        .WithMany("AcquiredMusicList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Mozart.Data.Entities.AttributiveItem", b =>
                {
                    b.HasOne("Mozart.Data.Entities.User", null)
                        .WithMany("AttributiveItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Mozart.Data.Entities.GiftItem", b =>
                {
                    b.HasOne("Mozart.Data.Entities.User", null)
                        .WithMany("GiftItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Mozart.Data.Entities.GiftMusic", b =>
                {
                    b.HasOne("Mozart.Data.Entities.User", null)
                        .WithMany("GiftMusics")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Mozart.Data.Entities.Loadout", b =>
                {
                    b.HasOne("Mozart.Data.Entities.User", null)
                        .WithOne("Loadout")
                        .HasForeignKey("Mozart.Data.Entities.Loadout", "UserId");
                });

            modelBuilder.Entity("Mozart.Data.Entities.Member", b =>
                {
                    b.HasOne("Mozart.Data.Entities.User", null)
                        .WithOne("Member")
                        .HasForeignKey("Mozart.Data.Entities.Member", "Username")
                        .HasPrincipalKey("Mozart.Data.Entities.User", "Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mozart.Data.Entities.MusicScoreRecord", b =>
                {
                    b.HasOne("Mozart.Data.Entities.User", null)
                        .WithMany("MusicScoreRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Mozart.Data.Entities.Penalty", b =>
                {
                    b.HasOne("Mozart.Data.Entities.User", null)
                        .WithOne("Penalty")
                        .HasForeignKey("Mozart.Data.Entities.Penalty", "UserId");
                });

            modelBuilder.Entity("Mozart.Data.Entities.UserMessage", b =>
                {
                    b.HasOne("Mozart.Data.Entities.User", null)
                        .WithMany("UserMessages")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Mozart.Data.Entities.UserRanking", b =>
                {
                    b.HasOne("Mozart.Data.Entities.User", null)
                        .WithOne("UserRanking")
                        .HasForeignKey("Mozart.Data.Entities.UserRanking", "UserId");
                });

            modelBuilder.Entity("Mozart.Data.Entities.UserRankingExtended", b =>
                {
                    b.HasOne("Mozart.Data.Entities.User", null)
                        .WithOne("UserRankingExtended")
                        .HasForeignKey("Mozart.Data.Entities.UserRankingExtended", "UserId");
                });

            modelBuilder.Entity("Mozart.Data.Entities.Wallet", b =>
                {
                    b.HasOne("Mozart.Data.Entities.User", null)
                        .WithOne("Wallet")
                        .HasForeignKey("Mozart.Data.Entities.Wallet", "UserId");
                });

            modelBuilder.Entity("Mozart.Data.Entities.User", b =>
                {
                    b.Navigation("AcquiredMusicList");

                    b.Navigation("AttributiveItems");

                    b.Navigation("GiftItems");

                    b.Navigation("GiftMusics");

                    b.Navigation("Loadout")
                        .IsRequired();

                    b.Navigation("Member")
                        .IsRequired();

                    b.Navigation("MusicScoreRecords");

                    b.Navigation("Penalty")
                        .IsRequired();

                    b.Navigation("UserMessages");

                    b.Navigation("UserRanking")
                        .IsRequired();

                    b.Navigation("UserRankingExtended")
                        .IsRequired();

                    b.Navigation("Wallet")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
