<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Configurations>Release;Debug</Configurations>
        <Platforms>x86;x64</Platforms>
        <IsPackable>false</IsPackable>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
        <OutputPath>..\..\..\..\Build\$(Configuration)\Identity\</OutputPath>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Identity.Data\Identity.Data.csproj" />
    </ItemGroup>

</Project>
